version: '3'
services:
  influxdb:
    image: qnib/plain-influxdb
    environment:
     - INFLUXDB_DATABASES=qframe
     - INFLUXDB_META_LOGGING=true
    volumes:
     - /opt/influxdb/shared
    ports:
     - 8083:8083
     - 8086:8086
  frontend:
    image: qnib/plain-grafana4
    ports:
     - 3000:3000
    environment:
     - INFLUXDB_HOST=qframe_influxdb
     - INFLUXDB_DB=qframe
    volumes:
     - ./resources/grafana/sql/:/opt/grafana/sql
  qframe-dev:
    image: qnib/uplain-golang
    command: wait.sh
    working_dir: /usr/local/src/github.com/qnib/qframe-handler-influxdb
    volumes:
      - ${GOPATH}/src/github.com/qnib/qframe-collector-docker-events:/usr/local/src/github.com/qnib/qframe-collector-docker-events
      - ${GOPATH}/src/github.com/qnib/qframe-collector-docker-stats:/usr/local/src/github.com/qnib/qframe-collector-docker-stats
      - ${GOPATH}/src/github.com/qnib/qframe-filter-docker-stats:/usr/local/src/github.com/qnib/qframe-filter-docker-stats
      - ${GOPATH}/src/github.com/qnib/qframe-handler-influxdb:/usr/local/src/github.com/qnib/qframe-handler-influxdb
      - ${GOPATH}/src/github.com/qnib/qframe-types:/usr/local/src/github.com/qnib/qframe-types
      - ${GOPATH}/src/github.com/qnib/qframe-utils:/usr/local/src/github.com/qnib/qframe-utils
      - /var/run/docker.sock:/var/run/docker.sock
      - ./resources/qnib/entry/:/opt/qnib/entry/
  qframe:
    image: qnib/qframe-handler-influxdb
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
